export const colors = [
	'main',
	'tomato',
	'red',
	'crimson',
	'pink',
	'plum',
	'purple',
	'violet',
	'indigo',
	'blue',
	'cyan',
	'teal',
	'green',
	'grass',
	'orange',
	'brown',
	'sky',
	'mint',
	'lime',
	'yellow',
	'amber',
	'gold',
	'bronze',
	'error',
	'info',
	'success',
	'warning',
] as const;

export const trueColors = [
	'main',
	'tomato',
	'red',
	'crimson',
	'pink',
	'plum',
	'purple',
	'violet',
	'indigo',
	'blue',
	'cyan',
	'teal',
	'green',
	'grass',
	'orange',
	'brown',
	'sky',
	'mint',
	'lime',
	'yellow',
	'amber',
	'gold',
	'bronze',
] as const;

export type RecastColors = (typeof colors)[number];

export type TrueColors = (typeof trueColors)[number];

export type SolidTextMappingType = Record<RecastColors, string>;

export const solidTextMapping: SolidTextMappingType = {
	main: 'white',
	tomato: 'white',
	red: 'white',
	crimson: 'white',
	pink: 'white',
	plum: 'white',
	purple: 'white',
	violet: 'white',
	indigo: 'white',
	blue: 'white',
	cyan: 'white',
	teal: 'white',
	green: 'white',
	grass: 'white',
	orange: 'white',
	brown: 'white',
	sky: 'black',
	mint: 'black',
	lime: 'black',
	yellow: 'black',
	amber: 'black',
	gold: 'white',
	bronze: 'white',
	error: 'white',
	info: 'black',
	success: 'white',
	warning: 'black',
};

export const stateColors = ['main', 'error', 'info', 'success', 'warning'];
