import { cva } from 'class-variance-authority';

export const switchTheme = cva(
	[
		'inline-flex',
		'items-center',
		'justify-start',
		'transition',
		'duration-250',
		'bg-gray-7 ',
		'peer-focus:ring-2',
		'peer-focus:ring-offset-0',
		'peer-focus:ring-gray-10',
		"after:content-['']",
		'after:transition',
		'after:duration-250',
		'after:bg-white',
		'after:border',
		'after:border-gray-10',
		'mr-2',
	],
	{
		variants: {
			color: {
				main: 'peer-checked:bg-main-10',
				tomato: 'peer-checked:bg-tomato-9',
				red: 'peer-checked:bg-red-9',
				crimson: 'peer-checked:bg-crimson-9',
				pink: 'peer-checked:bg-pink-9',
				plum: 'peer-checked:bg-plum-9',
				purple: 'peer-checked:bg-purple-9',
				violet: 'peer-checked:bg-violet-9',
				indigo: 'peer-checked:bg-indigo-9',
				blue: 'peer-checked:bg-blue-9',
				cyan: 'peer-checked:bg-cyan-9',
				teal: 'peer-checked:bg-teal-9',
				green: 'peer-checked:bg-green-9',
				grass: 'peer-checked:bg-grass-9',
				orange: 'peer-checked:bg-orange-9',
				brown: 'peer-checked:bg-brown-9',
				sky: 'peer-checked:bg-sky-9',
				mint: 'peer-checked:bg-mint-9',
				lime: 'peer-checked:bg-lime-9',
				yellow: 'peer-checked:bg-yellow-9',
				amber: 'peer-checked:bg-amber-9',
				gold: 'peer-checked:bg-gold-9',
				bronze: 'peer-checked:bg-bronze-9',
				error: 'peer-checked:bg-error-9',
				info: 'peer-checked:bg-info-9',
				success: 'peer-checked:bg-success-9',
				warning: 'peer-checked:bg-warning-9',
			},
			size: {
				sm: 'w-8 h-4 after:h-4 after:w-4 peer-checked:after:translate-x-4',
				base: 'w-10 h-5 after:h-5 after:w-5 peer-checked:after:translate-x-5',
				lg: 'w-12 h-6 after:h-6 after:w-6 peer-checked:after:translate-x-6',
			},
			rounded: {
				xs: 'rounded-xs after:rounded-xs',
				sm: 'rounded-sm after:rounded-sm',
				md: 'rounded-md after:rounded-md',
				lg: 'rounded-lg after:rounded-lg',
				full: 'rounded-full after:rounded-full',
			},
			error: { true: 'border-2 border-error-9 after:border-error-9' },
			disabled: { true: 'opacity-60' },
		},
		defaultVariants: {
			color: 'main',
			size: 'base',
		},
	},
);

export type SwitchTheme = typeof switchTheme;
